name: mdp_case_study
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.5.3
  auto_route: ^9.2.2
  easy_localization: ^3.0.7
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  very_good_analysis: ^6.0.0



flutter:


  uses-material-design: true

  
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
